### ISSUE TITLE
Missing municipalities in topojson/limits_IT_all.topo.json

### ISSUE THREAD

**Issue by mlocati** [openpolis/geojson-italy#7] opened 2021-03-23 09:18 UTC
I've compared the municipalities in the [`topojson/limits_IT_all.topo.json` file](https://github.com/openpolis/geojson-italy/blob/e89ef8c6194402f45539b3d7993d50fbe4a75e39/topojson/limits_IT_all.topo.json) with other municipality lists, and I've found that the following municipalities are not present in the `topojson/limits_IT_all.topo.json` file:

| ISTAT Code | Municipality |
|:---:|---|
| 001087 | Claviere |
| 013032 | Brunate |
| 015170 | Pero |
| 016027 | Blello |
| 016251 | Solza |
| 059033 | Ventotene |
| 063061 | Procida |
| 063069 | San Paolo Bel Sito |
| 071026 | Isole Tremiti |
| 093052 | Vajont |
| 096034 | Miagliano |

**Comment by guglielmo** [comment] 2021-03-24 10:17
I found out that the problem is in the topojson simplification, which is now at 5%.
A 20% simplification brings back all municipalities, but Biello (but that's going to be addressed in another issue).

This increases the size of the of the topojson files about 20%, bringing the size from 4.0MB to 4.8MB.

I think it is acceptable.

This is closed with 17bf6d44f4e1a8a22316fb7e5760a557ffeaf1dc, and has been tagges as 2021.2.

**Closed as completed by guglielmo** 2021-03-24 10:17 UTC

**Comment by guglielmo** [comment] 2021-03-24 10:18
As for Biello, it's being addressed in #8.
